services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "1234:443"
    restart: unless-stopped
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
  
  wordpress:
    build: ./requirements/wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_URL: ${WP_URL}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    volumes:
      - wordpress_files:/var/www/html
      - db_data:/var/lib/mysql
    depends_on:
      - maria-db
    networks:
      - inception

  maria-db:
    build: ./requirements/mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress_files:
  db_data: