services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: unless-stopped
    volumes:
      - /home/lberthal/data/wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
  
  wordpress:
    build: ./requirements/wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_URL: ${WP_URL}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    volumes:
      - /home/lberthal/data/wordpress:/var/www/html
    depends_on:
      - maria-db
    networks:
      - inception
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

  maria-db:
    build: ./requirements/mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - /home/lberthal/data/mariadb:/var/lib/mysql
    networks:
      - inception
    secrets:
      - db_root_password
      - db_password

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
